import { z } from 'zod'

const pianoSchema = z.object({
  id: z.string().min(1),
  name: z.string().min(1),
  venue: z.string(),
  city: z.string(),
  region: z.string().optional(),
  country: z.string(),
  countryCode: z.string().length(2),
  lat: z.number().min(-90).max(90),
  lng: z.number().min(-180).max(180),
  address: z.string().optional(),
  insideDirections: z.string().optional(),
  access: z.enum(['public', 'permissive', 'customers', 'limited', 'unknown']),
  accessNotes: z.string().optional(),
  status: z.enum([
    'available',
    'likely_available',
    'unknown',
    'limited_access',
    'seasonal_closed',
    'damaged_present',
    'missing_reported',
    'retired',
  ]),
  condition: z.enum(['excellent', 'good', 'fair', 'poor', 'unknown']),
  confidence: z.enum(['high', 'medium', 'low']),
  instrument: z.enum([
    'acoustic_piano',
    'digital_piano',
    'upright',
    'grand',
    'piano_unknown',
  ]),
  indoor: z.boolean().nullable(),
  operator: z.string().optional(),
  openingHours: z.string().optional(),
  lastVerified: z.string().optional(),
  source: z.enum(['openstreetmap', 'curated_seed']),
  sourceUrl: z.string().url().optional(),
  osm: z.object({
    type: z.enum(['node', 'way', 'relation']),
    id: z.number(),
    version: z.number().optional(),
    updatedAt: z.string().optional(),
    url: z.string().url(),
  }).optional(),
  tags: z.array(z.string()),
  notes: z.string().optional(),
})

export const pianosResponseSchema = z.object({
  pianos: z.array(pianoSchema),
  meta: z.object({
    source: z.enum(['api', 'fallback']),
    fetchedAt: z.string(),
    stale: z.boolean(),
    count: z.number().int().nonnegative(),
    message: z.string().optional(),
    attribution: z.string().optional(),
    licenseUrl: z.string().url().optional(),
  }),
})
